let mstClass = {
    "Saber":
    {
        "id":1,
        "name":"Saber",
        "attackRate":1000,
        "imageId":1
    },
    "Archer":
    {
        "id":2,
        "name":"Archer",
        "attackRate":950,
        "imageId":2
    },
    "Lancer":
    {
        "id":3,
        "name":"Lancer",
        "attackRate":1050,
        "imageId":3
    },
    "Rider":
    {
        "id":4,
        "name":"Rider",
        "attackRate":1000,
        "imageId":4
    },
    "Caster":
    {
        "id":5,
        "name":"Caster",
        "attackRate":900,
        "imageId":5
    },
    "Assassin":
    {
        "id":6,
        "name":"Assassin",
        "attackRate":900,
        "imageId":6
    },
    "Berserker":
    {
        "id":7,
        "name":"Berserker",
        "attackRate":1100,
        "imageId":7
    },
    "Shielder":
    {
        "id":8,
        "name":"Shielder",
        "attackRate":1000,
        "imageId":8
    },
    "Ruler":
    {
        "id":9,
        "name":"Ruler",
        "attackRate":1100,
        "imageId":9
    },
    "Alterego":
    {
        "id":10,
        "name":"Alterego",
        "attackRate":1000,
        "imageId":10
    },
    "Avenger":
    {
        "id":11,
        "name":"Avenger",
        "attackRate":1100,
        "imageId":11
    },
    "MoonCancer":
    {
        "id":12,
        "name":"MoonCancer",
        "attackRate":1000,
        "imageId":12
    },
    "Foreigner":
    {
        "id":25,
        "name":"Foreigner",
        "attackRate":1000,
        "imageId":25
    }
};